"""Backtest validation: is the strategy actually any good?

A plan that looks clever on paper is worthless if it was built on wait times
that never materialised. So every strategy here is scored the same way:

1. Take a day for which we have a *complete* trace of what every queue did --
   either banked by the collector or generated by the simulator.
2. Run the strategy **online**. At each replan point the strategy is handed
   only the readings that existed at that moment. It cannot see the future.
3. Advance the party through the day using the *actual* waits from the trace,
   not the ones the strategy predicted. Plans slip, and the slip is the point.
4. Score what really happened.

The headline number is the **optimality gap**: the same day is also solved by
an oracle that is given the entire day's true waits up front. The oracle is
an upper bound on what any strategy could possibly have achieved with perfect
foresight. A strategy scoring 90% of the oracle is 10% away from the best any
planner could do, and no amount of cleverness can close a gap caused by
information that simply was not available at the time.

Baselines are included because "our strategy scores 400" means nothing on its
own. It has to beat what a reasonable family would do without any of this.
"""

from __future__ import annotations

import dataclasses
import statistics
from dataclasses import dataclass, field
from datetime import timedelta

from .config import CHILD, EVERYONE, FAMILY, TripConfig
from .forecast import POSTED_BIAS, Forecaster
from .model import Catalog, Plan, PlanItem
from .optimizer import Optimizer
from .sources.replay import ReplaySource
from .sources.simulator import SimulatedSource, simulate_day
from .store import Store
from .walk import WalkMatrix


# ---------------------------------------------------------------------------
# Oracles
# ---------------------------------------------------------------------------

class PerfectOracle:
    """Knows every queue's true length at every moment of the day.

    Not a strategy anybody can run -- it is the ceiling that real strategies
    are measured against.
    """

    def __init__(self, trace_source, catalog: Catalog):
        self.src = trace_source
        self.cat = catalog
        self._cache: dict = {}

    def _posted(self, ride_id: str, minute: int) -> float | None:
        return self.src.wait_at(ride_id, int(minute))

    def expected_queue_min(self, ride_id: str, arrive_minute: int) -> float:
        key = (ride_id, int(arrive_minute) // 5)
        hit = self._cache.get(key)
        if hit is not None:
            return hit
        w = self._posted(ride_id, arrive_minute)
        val = 240.0 if w is None else max(5.0, w * POSTED_BIAS)
        self._cache[key] = val
        return val

    def single_rider_wait(self, ride_id: str, at_minute: int) -> float | None:
        a = self.cat.get(ride_id)
        if a is None or not a.single_rider:
            return None
        w = self._posted(ride_id, at_minute)
        if w is None:
            return None
        return max(5.0, min(w, w * 0.33 + 5))

    def premier_return(self, ride_id: str, book_minute: int) -> tuple[int, float] | None:
        a = self.cat.get(ride_id)
        if a is None or not a.premier_access:
            return None
        w = self._posted(ride_id, book_minute) or 30
        lead = int(min(180, 20 + 0.55 * w))
        return book_minute + lead, min(20.0, 5 + 0.12 * w)

    def availability(self, ride_id: str, at_minute: int) -> float:
        return 0.0 if self._posted(ride_id, at_minute) is None else 1.0


# ---------------------------------------------------------------------------
# Execution: walking a plan through the real day
# ---------------------------------------------------------------------------

@dataclass
class DayResult:
    day: str
    strategy: str
    executed: Plan
    child_rides: int = 0
    distinct: int = 0
    must_done: int = 0
    must_total: int = 0
    family_queue_min: int = 0
    walk_min: int = 0
    value: float = 0.0
    abandoned: int = 0

    def as_row(self) -> dict:
        return {
            "day": self.day,
            "strategy": self.strategy,
            "value": round(self.value, 1),
            "child_rides": self.child_rides,
            "distinct": self.distinct,
            "must_do": f"{self.must_done}/{self.must_total}",
            "queue_min": self.family_queue_min,
            "walk_min": self.walk_min,
            "abandoned": self.abandoned,
        }


class Executor:
    """Walks a planned day through the trace of what actually happened.

    A planned 20-minute wait that turns out to be 55 pushes everything after
    it later. Rides that no longer fit before closing are dropped and counted
    as abandoned. This is what separates a schedule from a fantasy.
    """

    #: If the real queue is this many minutes longer than planned, the party
    #: gives up and the replanner picks something else.
    BAIL_THRESHOLD = 30

    def __init__(self, catalog: Catalog, cfg: TripConfig, truth, walk: WalkMatrix):
        self.cat = catalog
        self.cfg = cfg
        self.truth = truth
        self.walk = walk

    def run(self, plan: Plan, upto: int | None = None,
            clock0: dict | None = None, loc0: dict | None = None
            ) -> tuple[Plan, int, dict]:
        """Execute ``plan`` against the truth up to ``upto`` minutes.

        Returns (what actually happened, the clock when execution stopped,
        per-track end state so a replan can pick up from here).

        ``upto`` is a *commitment* horizon, not a truncation: anything the plan
        starts before it runs to completion. You cannot replan your way out of
        a queue you are already standing in -- only walk away from it, which is
        what ``BAIL_THRESHOLD`` covers.
        """
        done: list[PlanItem] = []
        abandoned = 0
        clock = dict(clock0) if clock0 else {0: None, 1: None}   # track -> free-at
        loc = dict(loc0) if loc0 else {0: WalkMatrix.ENTRANCE, 1: WalkMatrix.ENTRANCE}

        for item in sorted(plan.items, key=lambda i: (i.start, i.track)):
            tr = item.track
            start = item.start if clock[tr] is None else max(item.start, clock[tr])
            if upto is not None and start >= upto:
                break

            if item.kind != "ride":
                end = start + (item.end - item.start)
                done.append(PlanItem(**{**item.__dict__, "start": start,
                                        "board": start, "end": end}))
                clock[tr] = end
                if item.kind == "meal":
                    clock[0] = clock[1] = end
                continue

            a = self.cat[item.ride_id]
            walk = self.walk.int_minutes(loc[tr], a.id, with_child=(tr == 0))
            arrive = max(start + walk, self.cfg.open_minute(a.park))

            actual = self._actual_wait(item, arrive)
            if actual is None:
                abandoned += 1              # ride was down when they got there
                clock[tr] = arrive
                loc[tr] = a.id
                continue

            board = int(arrive + actual)
            end = board + a.duration_min
            if end > self.cfg.close_minute(a.park):
                abandoned += 1
                clock[tr] = arrive
                continue
            if actual - item.predicted_wait > self.BAIL_THRESHOLD:
                # Queue is far worse than advertised; walk away and replan.
                abandoned += 1
                clock[tr] = arrive + 5
                loc[tr] = a.id
                continue

            done.append(PlanItem(**{**item.__dict__, "start": start, "board": board,
                                    "end": end, "walk_min": walk,
                                    "actual_wait": int(actual)}))
            clock[tr] = end
            loc[tr] = a.id

        stop = max((c for c in clock.values() if c is not None), default=self.cfg.day_start())
        state = {"clock": clock, "loc": loc}
        return Plan(items=done, value=sum(i.value for i in done)), stop, {
            **state, "abandoned": abandoned}

    def _actual_wait(self, item: PlanItem, arrive: int) -> float | None:
        if item.mode == "premier":
            return float(item.predicted_wait)    # a return window is a promise
        posted = self.truth.wait_at(item.ride_id, arrive)
        if posted is None:
            return None
        if item.mode == "single_rider":
            return max(5.0, min(posted, posted * 0.33 + 5))
        return max(5.0, posted * POSTED_BIAS)


# ---------------------------------------------------------------------------
# Strategies under test
# ---------------------------------------------------------------------------

class Strategy:
    name = "base"

    def plan(self, catalog: Catalog, cfg: TripConfig, truth, walk: WalkMatrix,
             store: Store | None) -> Plan:
        raise NotImplementedError


class OptimizerStrategy(Strategy):
    """The real thing: replans through the day on live data only."""

    name = "optimizer_online"

    def __init__(self, replan_interval: int | None = None):
        self.replan_interval = replan_interval

    def plan(self, catalog, cfg, truth, walk, store) -> Plan:
        interval = self.replan_interval or cfg.strategy.replan_interval_min
        forecaster = Forecaster.from_catalog(catalog, cfg, store)
        executor = Executor(catalog, cfg, truth, walk)
        # Replans are frequent and only the next move has to be right, so they
        # run at a narrower beam than the once-a-day opening plan.
        replan_cfg = cfg.with_overrides(
            strategy=dataclasses.replace(cfg.strategy,
                                         beam_width=cfg.strategy.replan_beam_width))

        clock = cfg.day_start()
        end_of_day = cfg.day_end()
        realised: list[PlanItem] = []
        abandoned = 0
        seen: set[str] = set()
        adult_seen: set[str] = set()
        loc = {0: WalkMatrix.ENTRANCE, 1: WalkMatrix.ENTRANCE}
        start = {0: clock, 1: clock}
        # Premier Access windows already bought carry across replans, as does
        # the money spent on them.
        pa_holds: tuple = ()
        pa_used = 0

        guard = 0
        while guard < 400:
            guard += 1
            # The party replans whenever the earlier of the two tracks comes
            # free -- that is the moment somebody has to decide what is next.
            clock = min(start[0], start[1])
            if clock >= end_of_day:
                break

            # Only what the party could actually see at this moment. Nothing
            # from later in the day is visible to the planner.
            snapshot = {
                rid: (clock, truth.wait_at(rid, clock)) for rid in catalog.ids()
            }
            forecaster.observe(snapshot)

            live_holds = tuple(h for h in pa_holds if h[0] not in seen)
            remaining_must = tuple(m for m in cfg.must_do if m not in seen)
            cursor_cfg = replan_cfg.with_overrides(must_do=remaining_must)

            opt = Optimizer(catalog, cursor_cfg, forecaster, walk)
            opt.resume_from(
                t0=start[0], t1=start[1], loc0=loc[0], loc1=loc[1],
                child_done=frozenset(seen), adult_done=frozenset(adult_seen),
                pa_holds=live_holds, pa_used=pa_used,
                lunch_done=any(i.kind == "meal" for i in realised),
            )
            plan = opt.solve()
            if not plan.items:
                break

            horizon = min(end_of_day, clock + interval)
            chunk, stop, st = executor.run(plan, upto=horizon,
                                           clock0=start, loc0=loc)
            abandoned += st["abandoned"]

            if not chunk.items:
                # Nothing was worth committing to; idle both tracks forward so
                # the loop cannot spin on the same minute forever.
                start = {tr: max(v, clock + 10) for tr, v in start.items()}
                continue

            realised.extend(chunk.items)
            for i in chunk.items:
                if i.kind == "ride" and i.ride_id:
                    (seen if i.group & CHILD else adult_seen).add(i.ride_id)
                elif i.kind == "book_pa" and i.ride_id and i.return_minute is not None:
                    pa_holds += ((i.ride_id, i.return_minute, float(i.predicted_wait)),)
                    pa_used += 1
            progressed = False
            for tr in (0, 1):
                if st["clock"][tr] is not None and st["clock"][tr] > start[tr]:
                    start[tr] = st["clock"][tr]
                    progressed = True
                loc[tr] = st["loc"][tr]
            if not progressed:
                start = {tr: max(v, clock + 10) for tr, v in start.items()}

        out = Plan(items=realised, value=sum(i.value for i in realised))
        out.notes.append(
            f"online replans={guard} interval={interval}min "
            f"abandoned={abandoned} premier_access_bought={pa_used}"
        )
        return out


class OracleStrategy(Strategy):
    """Perfect foresight. The ceiling, not a plan anyone can follow."""

    name = "oracle_upper_bound"

    def plan(self, catalog, cfg, truth, walk, store) -> Plan:
        oracle = PerfectOracle(truth, catalog)
        return Optimizer(catalog, cfg, oracle, walk).solve()


class GreedyNearestStrategy(Strategy):
    """What a family does with the official app open: from wherever you are,
    go to whatever has the shortest wait right now. No lookahead at all."""

    name = "greedy_shortest_wait"

    def plan(self, catalog, cfg, truth, walk, store) -> Plan:
        items: list[PlanItem] = []
        clock = cfg.day_start()
        loc = WalkMatrix.ENTRANCE
        done: set[str] = set()
        height = cfg.party.child_height_cm
        lunch_done = False
        lunch_at = 12 * 60 + 30

        while clock < cfg.day_end():
            if not lunch_done and clock >= lunch_at:
                items.append(PlanItem("meal", None, "Lunch", "DLP", "", EVERYONE,
                                      clock, clock, clock + cfg.lunch_window[2], ""))
                clock += cfg.lunch_window[2]
                lunch_done = True
                continue
            best = None
            for a in catalog:
                if a.id in done or not a.admits(height) or a.id in cfg.skip:
                    continue
                w = truth.wait_at(a.id, clock)
                if w is None:
                    continue
                walk_min = walk.int_minutes(loc, a.id, True)
                cost = walk_min + w * POSTED_BIAS + a.duration_min
                if best is None or cost < best[0]:
                    best = (cost, a, walk_min, w)
            if best is None:
                clock += 15
                continue
            cost, a, walk_min, w = best
            arrive = clock + walk_min
            board = int(arrive + w * POSTED_BIAS)
            end = board + a.duration_min
            if end > cfg.close_minute(a.park):
                break
            items.append(PlanItem("ride", a.id, a.name, a.park, a.land, FAMILY,
                                  clock, board, end, "standby",
                                  predicted_wait=int(w), actual_wait=int(w),
                                  track=0, value=a.appeal * cfg.strategy.child_value_weight,
                                  walk_min=walk_min))
            done.add(a.id)
            clock, loc = end, a.id
        return Plan(items=items, value=sum(i.value for i in items))


class PopularityRouteStrategy(Strategy):
    """The internet's advice: rope-drop the headliners in popularity order and
    work down the list, land by land. Fixed before you arrive; ignores the day."""

    name = "fixed_popularity_route"

    def plan(self, catalog, cfg, truth, walk, store) -> Plan:
        height = cfg.party.child_height_cm
        order = sorted(
            (a for a in catalog if a.admits(height) and a.id not in cfg.skip),
            key=lambda a: (-a.appeal, a.typical_peak_wait),
        )
        items: list[PlanItem] = []
        clock = cfg.day_start()
        loc = WalkMatrix.ENTRANCE
        lunch_done = False
        for a in order:
            if not lunch_done and clock >= 12 * 60 + 30:
                items.append(PlanItem("meal", None, "Lunch", "DLP", "", EVERYONE,
                                      clock, clock, clock + cfg.lunch_window[2], ""))
                clock += cfg.lunch_window[2]
                lunch_done = True
            walk_min = walk.int_minutes(loc, a.id, True)
            arrive = max(clock + walk_min, cfg.open_minute(a.park))
            w = truth.wait_at(a.id, arrive)
            if w is None:
                continue
            board = int(arrive + w * POSTED_BIAS)
            end = board + a.duration_min
            if end > cfg.close_minute(a.park):
                continue
            items.append(PlanItem("ride", a.id, a.name, a.park, a.land, FAMILY,
                                  clock, board, end, "standby",
                                  predicted_wait=int(w), actual_wait=int(w),
                                  track=0, value=a.appeal * cfg.strategy.child_value_weight,
                                  walk_min=walk_min))
            clock, loc = end, a.id
        return Plan(items=items, value=sum(i.value for i in items))


DEFAULT_STRATEGIES: list[Strategy] = [
    OptimizerStrategy(),
    GreedyNearestStrategy(),
    PopularityRouteStrategy(),
    OracleStrategy(),
]


# ---------------------------------------------------------------------------
# Harness
# ---------------------------------------------------------------------------

def score(plan: Plan, cfg: TripConfig, day: str, name: str, abandoned: int = 0) -> DayResult:
    child = [i for i in plan.rides() if i.group & CHILD]
    distinct = {i.ride_id for i in child}
    must = set(cfg.must_do)
    return DayResult(
        day=day, strategy=name, executed=plan,
        child_rides=len(child),
        distinct=len(distinct),
        must_done=len(must & distinct),
        must_total=len(must),
        family_queue_min=sum(i.wait_min for i in plan.rides(track=0)),
        walk_min=sum(i.walk_min for i in plan.items),
        value=plan.value,
        abandoned=abandoned,
    )


def backtest_day(catalog: Catalog, cfg: TripConfig, truth, day: str,
                 strategies: list[Strategy] | None = None,
                 store: Store | None = None) -> list[DayResult]:
    strategies = strategies or DEFAULT_STRATEGIES
    walk = WalkMatrix(catalog, cfg.party.walk_speed_family_mps,
                      cfg.party.walk_speed_adult_mps)
    executor = Executor(catalog, cfg, truth, walk)
    results = []
    for strat in strategies:
        plan = strat.plan(catalog, cfg, truth, walk, store)
        if isinstance(strat, OptimizerStrategy):
            # Already executed against the truth during its own replan loop.
            executed, abandoned = plan, 0
        else:
            executed, _, st = executor.run(plan)
            abandoned = st["abandoned"]
        results.append(score(executed, cfg, day, strat.name, abandoned))
    return results


def simulated_days(catalog: Catalog, cfg: TripConfig, n: int = 12,
                   seed: int = 1234) -> list[tuple[str, SimulatedSource, float]]:
    """A spread of plausible days around the trip date.

    Crowd levels are drawn across the range late November actually produces --
    quiet midweek days through busy Christmas-season weekends -- so a strategy
    cannot win by being tuned to one crowd level.
    """
    import random
    rng = random.Random(seed)
    out = []
    for k in range(n):
        d = cfg.trip_date - timedelta(days=7 * k)
        crowd = rng.choice([3.5, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.5])
        traces = simulate_day(catalog, d, crowd_index=crowd,
                              open_min=cfg.open_minute("DLP"),
                              close_min=cfg.close_minute("DLP"),
                              seed=seed + k)
        out.append((d.isoformat(), SimulatedSource(catalog, traces), crowd))
    return out


@dataclass
class BacktestReport:
    rows: list[DayResult] = field(default_factory=list)
    days: list[str] = field(default_factory=list)
    crowd: dict[str, float] = field(default_factory=dict)

    def by_strategy(self) -> dict[str, list[DayResult]]:
        out: dict[str, list[DayResult]] = {}
        for r in self.rows:
            out.setdefault(r.strategy, []).append(r)
        return out

    def aggregate(self) -> list[dict]:
        groups = self.by_strategy()
        oracle = {r.day: r.value for r in groups.get(OracleStrategy.name, [])}
        out = []
        for name, rows in groups.items():
            gaps = [rows_value_ratio(r, oracle) for r in rows]
            gaps = [g for g in gaps if g is not None]
            out.append({
                "strategy": name,
                "days": len(rows),
                "mean_value": round(statistics.fmean(r.value for r in rows), 1),
                "mean_child_rides": round(statistics.fmean(r.child_rides for r in rows), 1),
                "mean_distinct": round(statistics.fmean(r.distinct for r in rows), 1),
                "must_do_rate": round(
                    statistics.fmean(r.must_done / r.must_total if r.must_total else 1.0
                                     for r in rows), 3),
                "mean_queue_min": round(statistics.fmean(r.family_queue_min for r in rows)),
                "mean_walk_min": round(statistics.fmean(r.walk_min for r in rows)),
                "pct_of_oracle": round(100 * statistics.fmean(gaps), 1) if gaps else None,
                "worst_day_pct": round(100 * min(gaps), 1) if gaps else None,
            })
        out.sort(key=lambda r: -(r["pct_of_oracle"] or 0))
        return out

    def render(self) -> str:
        rows = self.aggregate()
        head = (f"{'strategy':24} {'days':>4} {'value':>7} {'rides':>6} {'uniq':>5} "
                f"{'must':>6} {'queue':>6} {'walk':>5} {'%oracle':>8} {'worst':>6}")
        lines = [head, "-" * len(head)]
        for r in rows:
            lines.append(
                f"{r['strategy']:24} {r['days']:>4} {r['mean_value']:>7.1f} "
                f"{r['mean_child_rides']:>6.1f} {r['mean_distinct']:>5.1f} "
                f"{r['must_do_rate']:>6.2f} {r['mean_queue_min']:>6} "
                f"{r['mean_walk_min']:>5} "
                f"{(r['pct_of_oracle'] if r['pct_of_oracle'] is not None else 0):>8.1f} "
                f"{(r['worst_day_pct'] if r['worst_day_pct'] is not None else 0):>6.1f}"
            )
        return "\n".join(lines)


def rows_value_ratio(r: DayResult, oracle: dict[str, float]) -> float | None:
    ceiling = oracle.get(r.day)
    if not ceiling:
        return None
    return r.value / ceiling


def run_backtest(catalog: Catalog, cfg: TripConfig, days: int = 12,
                 store: Store | None = None, use_stored: bool = False,
                 strategies: list[Strategy] | None = None,
                 seed: int = 1234) -> BacktestReport:
    """Score every strategy across many days and report the optimality gap."""
    report = BacktestReport()

    if use_stored and store is not None:
        stored = store.days()
        if not stored:
            raise RuntimeError(
                "no collected days in the database yet -- run `collect` for a "
                "few days first, or drop --use-stored to backtest on simulated days"
            )
        pool = [(d, ReplaySource(store, catalog, d), None) for d in stored[-days:]]
    else:
        pool = simulated_days(catalog, cfg, n=days, seed=seed)

    for day, truth, crowd in pool:
        report.days.append(day)
        if crowd is not None:
            report.crowd[day] = crowd
        report.rows.extend(backtest_day(catalog, cfg, truth, day, strategies, store))
    return report
